# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-02 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleCompletionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('completion_time_in_seconds', models.IntegerField()),
                ('moves_count', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['completion_time_in_seconds', 'moves_count', 'date_created'],
            },
        ),
    ]
