# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzlecompletiondetail',
            options={'ordering': ['completion_time_in_seconds', 'moves_count', '-date_created']},
        ),
    ]
